### ISSUE TITLE
[Database] Create a database to store user input 

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/website-authentication-process#3]

**Comment by then00bprogrammer** [comment]
elaborate a bit?

**Comment by Sanket1308** [comment]
You have to basically implement user sign-up and sign-in process.
- You can use any language/Database 
- You can create sample Sign-up and Forget page
- You  have to create a sample home(landing) page which will be shown after signup/sign in. Landing page will just have a landing page name at top (no features)

You **don't** have to complete all points mentioned above in one go. Complete one thing at a time and send PR

**Comment by Ravina-Deogadkar** [comment]
Can I take work on this task?

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀

**Comment by Ravina-Deogadkar** [comment]
Thanks

**Comment by Ravina-Deogadkar** [comment]
Added pull request https://github.com/Sanket1308/website-authentication-process/pull/27
